# Generated by Django 3.1.12 on 2021-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_manager_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
